-- Z-Vault Pro D1 Database Schema
-- Run: wrangler d1 execute z-vault-pro-db --file=./src/db/schema.sql

-- Transaction log: every GasFree relay attempt
CREATE TABLE IF NOT EXISTS transactions (
  id          TEXT    PRIMARY KEY,           -- UUID generated by worker
  user_address TEXT   NOT NULL,              -- Sender's TRON address
  recipient   TEXT    NOT NULL,              -- Recipient TRON address
  amount      TEXT    NOT NULL,              -- Transfer amount (USDT, string for precision)
  fee         TEXT    NOT NULL DEFAULT '1.00', -- Platform fee charged to user (USDT)
  provider_fee TEXT,                         -- What GasFree provider actually charged
  profit      TEXT,                          -- Net margin (fee - provider_fee)
  tx_hash     TEXT,                          -- On-chain tx hash (from provider response)
  status      TEXT    NOT NULL DEFAULT 'pending', -- pending | success | failed
  network     TEXT    NOT NULL DEFAULT 'nile',   -- nile | mainnet
  created_at  INTEGER NOT NULL,              -- Unix timestamp (ms)
  updated_at  INTEGER NOT NULL
);

-- Index for quick address lookup
CREATE INDEX IF NOT EXISTS idx_tx_user_address ON transactions(user_address);
CREATE INDEX IF NOT EXISTS idx_tx_status ON transactions(status);
CREATE INDEX IF NOT EXISTS idx_tx_created ON transactions(created_at DESC);

-- Audit log: security events (logins, relay attempts, errors)
CREATE TABLE IF NOT EXISTS audit_log (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  event       TEXT    NOT NULL,              -- relay_attempt | relay_success | relay_error | rate_limit | blacklist_hit
  user_address TEXT,                         -- TRON address if known
  ip_address  TEXT,                          -- Requester IP
  user_agent  TEXT,                          -- Browser UA string (truncated)
  details     TEXT,                          -- JSON payload for debugging
  created_at  INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_event ON audit_log(event);
CREATE INDEX IF NOT EXISTS idx_audit_ip ON audit_log(ip_address);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at DESC);

-- Address blacklist: known scam/phishing TRON addresses
CREATE TABLE IF NOT EXISTS blacklist (
  address     TEXT    PRIMARY KEY,           -- TRON address
  reason      TEXT    NOT NULL,              -- phishing | scam | frozen
  added_at    INTEGER NOT NULL
);

-- Profit summary: daily aggregated stats  
CREATE TABLE IF NOT EXISTS profit_summary (
  date        TEXT    PRIMARY KEY,          -- YYYY-MM-DD
  tx_count    INTEGER NOT NULL DEFAULT 0,
  total_revenue TEXT  NOT NULL DEFAULT '0',
  total_cost  TEXT    NOT NULL DEFAULT '0',
  total_profit TEXT   NOT NULL DEFAULT '0',
  updated_at  INTEGER NOT NULL
);

-- Withdrawals: tracks profit withdrawals to treasury
CREATE TABLE IF NOT EXISTS withdrawals (
  id          TEXT    PRIMARY KEY,
  amount      TEXT    NOT NULL,
  treasury    TEXT    NOT NULL,
  status      TEXT    NOT NULL DEFAULT 'recorded',
  network     TEXT    NOT NULL DEFAULT 'nile',
  created_at  INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_created ON withdrawals(created_at DESC);
